import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { lstat, mkdir, mkdtemp, readFile, readdir, rm, utimes, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import {
  associateWorkspace,
  initializeWorkspaceIdentity,
  listParticipants,
  readConversationSelection,
  readWorkspaceIdentity,
  registerParticipant,
  relabelParticipant,
  resolveActiveParticipant,
  rotateWorkspaceIdentity,
  selectParticipant,
} from './workspace.js';
import {
  appendMessage,
  approveConversation,
  conversationPath,
  createConversation,
  joinConversation,
  listConversations,
  readConversation,
  readConversationRecords,
  revokeConversationParticipant,
  countRevisionApprovals,
} from './store.js';
import {
  readContractState,
  syncContractToWorkspace,
  updateConversationContract,
  writeConversationContract,
} from './contract.js';
import { withFileLock } from './atomic.js';

const execFileAsync = promisify(execFile);
const storeModulePath = fileURLToPath(new URL('./store.js', import.meta.url));
const contractModulePath = fileURLToPath(new URL('./contract.js', import.meta.url));
const atomicModulePath = fileURLToPath(new URL('./atomic.js', import.meta.url));
const workspaceModulePath = fileURLToPath(new URL('./workspace.js', import.meta.url));

async function temporaryWorkspace(t: test.TestContext, prefix: string): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), prefix));
  t.after(async () => rm(directory, { recursive: true, force: true }));
  return directory;
}

test('contracts are conversation scoped and the compatibility file is only the selected view', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-scoped-contract-');
  await initializeWorkspaceIdentity(cwd);
  const first = await createConversation(cwd, { id: 'first', topic: 'First contract' });
  await writeConversationContract(cwd, { conversationId: first.id, topic: first.topic });
  await updateConversationContract(cwd, first.id, {
    sections: [{ heading: 'Agreed Changes', content: 'First body' }],
  });
  const firstState = await readContractState(cwd, first.id);

  const second = await createConversation(cwd, { id: 'second', topic: 'Second contract' });
  await writeConversationContract(cwd, { conversationId: second.id, topic: second.topic });
  await updateConversationContract(cwd, second.id, {
    sections: [{ heading: 'Agreed Changes', content: 'Second body' }],
  });
  const secondState = await readContractState(cwd, second.id);

  assert.notEqual(firstState.path, secondState.path);
  assert.match(await readFile(firstState.path, 'utf8'), /First body/);
  assert.doesNotMatch(await readFile(firstState.path, 'utf8'), /Second body/);
  assert.match(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), /Second body/);
});

test('interrupted compatibility selection recovers matching metadata and generated bytes', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-selection-recovery-');
  const conversation = await createConversation(cwd, { id: 'selection-recovery', topic: 'Selection recovery' });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  await updateConversationContract(cwd, conversation.id, {
    sections: [{ heading: 'Agreed Changes', content: 'Recovered projection bytes' }],
  });
  const other = await createConversation(cwd, { id: 'selection-other', topic: 'Other selection' });
  await writeConversationContract(cwd, { conversationId: other.id, topic: other.topic });
  assert.match(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), /Other selection/);

  const childSelect = `import { selectConversation } from ${JSON.stringify(workspaceModulePath)}; await selectConversation(process.argv[1], 'selection-recovery', true);`;
  await assert.rejects(execFileAsync(
    process.execPath,
    ['--input-type=module', '-e', childSelect, cwd],
    { env: {
      ...process.env,
      AGENTLINK_TEST_FAIL_TRANSACTION_KEY: 'compatibility-selection-recovery',
      AGENTLINK_TEST_CRASH_AFTER_TRANSACTION_WRITE: '1',
    } },
  ));

  await initializeWorkspaceIdentity(cwd);
  const selection = await readConversationSelection(cwd);
  const state = await readContractState(cwd, conversation.id);
  assert.equal(selection?.conversationId, conversation.id);
  assert.equal(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), await readFile(state.path, 'utf8'));
  assert.match(selection?.compatibilityDigest ?? '', /^[a-f0-9]{64}$/);
});

test('sync associates two workspaces with one authoritative bus and timeline', async (t) => {
  const source = await temporaryWorkspace(t, 'agentlink-bus-source-');
  const peer = await temporaryWorkspace(t, 'agentlink-bus-peer-');
  await initializeWorkspaceIdentity(source);
  await initializeWorkspaceIdentity(peer);
  const conversation = await createConversation(source, { id: 'shared', topic: 'Shared authority' });
  await writeConversationContract(source, { conversationId: conversation.id, topic: conversation.topic });

  await syncContractToWorkspace(source, peer, conversation.id);
  await joinConversation(peer, conversation.id);
  await appendMessage(peer, conversation.id, { role: 'assistant', body: 'Written from peer' });

  assert.equal(conversationPath(source, conversation.id), conversationPath(peer, conversation.id));
  assert.equal((await readConversation(source, conversation.id)).messages[0]?.body, 'Written from peer');
  assert.equal((await readContractState(peer, conversation.id)).path, (await readContractState(source, conversation.id)).path);
});

test('legacy logs and marked contracts migrate idempotently without deleting audit records', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-legacy-migration-');
  const legacyDirectory = join(cwd, '.agentlink', 'conversations');
  await mkdir(legacyDirectory, { recursive: true });
  const records = [
    { type: 'conversation', id: 'legacy', topic: 'Legacy topic', createdAt: '2026-01-01T00:00:00.000Z', status: 'open', requiredApprovals: 1 },
    { type: 'approval', from: 'old-label', timestamp: '2026-01-01T00:01:00.000Z' },
  ];
  const legacyLog = `${records.map((record) => JSON.stringify(record)).join('\n')}\n`;
  await writeFile(join(legacyDirectory, 'legacy.jsonl'), legacyLog, 'utf8');
  const legacyContract = '# AgentLink Contract\n\n<!-- agentlink-conversation: legacy -->\n\n## Topic\n\nLegacy topic\n\n## Status\n\nProposed\n';
  await writeFile(join(cwd, '.agentlink', 'CONTRACT.md'), legacyContract, 'utf8');

  await initializeWorkspaceIdentity(cwd);
  await initializeWorkspaceIdentity(cwd);

  const conversation = await readConversation(cwd, 'legacy');
  assert.equal(conversation.approvals.length, 1);
  assert.equal(conversation.approvals[0]?.from, 'old-label');
  assert.equal(await readFile(join(legacyDirectory, 'legacy.jsonl'), 'utf8'), legacyLog);
  assert.equal(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), legacyContract);
  assert.equal(await readFile((await readContractState(cwd, 'legacy')).path, 'utf8'), legacyContract);
});

test('completed legacy imports stay idempotent after authoritative writes', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-legacy-rerun-');
  const legacyDirectory = join(cwd, '.agentlink', 'conversations');
  await mkdir(legacyDirectory, { recursive: true });
  const legacyLog = `${JSON.stringify({
    type: 'conversation', id: 'legacy-rerun', topic: 'Legacy rerun', createdAt: '2026-01-01T00:00:00.000Z', status: 'open',
  })}\n`;
  await writeFile(join(legacyDirectory, 'legacy-rerun.jsonl'), legacyLog, 'utf8');
  const legacyContract = '# AgentLink Contract\n\n<!-- agentlink-conversation: legacy-rerun -->\n\n## Topic\n\nLegacy rerun\n\n## Agreed Changes\n\nOld body\n\n## Status\n\nDraft\n';
  await writeFile(join(cwd, '.agentlink', 'CONTRACT.md'), legacyContract, 'utf8');

  await initializeWorkspaceIdentity(cwd);
  await joinConversation(cwd, 'legacy-rerun');
  await appendMessage(cwd, 'legacy-rerun', { role: 'assistant', body: 'New authoritative message' });
  await updateConversationContract(cwd, 'legacy-rerun', {
    sections: [{ heading: 'Agreed Changes', content: 'New authoritative body' }],
  });
  await initializeWorkspaceIdentity(cwd);
  await initializeWorkspaceIdentity(cwd);

  assert.equal(await readFile(join(legacyDirectory, 'legacy-rerun.jsonl'), 'utf8'), legacyLog);
  const conversation = await readConversation(cwd, 'legacy-rerun');
  assert.deepEqual(conversation.messages.map((message) => message.body), ['New authoritative message']);
  assert.match(await readFile((await readContractState(cwd, 'legacy-rerun')).path, 'utf8'), /New authoritative body/);
});

test('unmarked legacy contract is preserved but never assigned to an arbitrary conversation', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-unassigned-contract-');
  await mkdir(join(cwd, '.agentlink', 'conversations'), { recursive: true });
  await writeFile(join(cwd, '.agentlink', 'CONTRACT.md'), '# Old contract\n\n## Status\n\nDraft\n', 'utf8');
  await writeFile(join(cwd, '.agentlink', 'conversations', 'only.jsonl'), `${JSON.stringify({
    type: 'conversation', id: 'only', topic: 'Only conversation', createdAt: '2026-01-01T00:00:00.000Z', status: 'open',
  })}\n`, 'utf8');

  await initializeWorkspaceIdentity(cwd);
  const state = await readContractState(cwd, 'only');
  assert.equal(state.status, null);
  assert.match(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), /Old contract/);
  assert.equal(await readFile(join(cwd, '.agentlink', 'legacy', 'CONTRACT.unassigned.md'), 'utf8'), '# Old contract\n\n## Status\n\nDraft\n');
});

test('workspace and participant identities remain distinct across relabel and clone repair', async (t) => {
  const original = await temporaryWorkspace(t, 'agentlink-identity-original-');
  const clone = await temporaryWorkspace(t, 'agentlink-identity-clone-');
  await initializeWorkspaceIdentity(original);
  const first = await registerParticipant(original, { displayName: 'backend-agent' });
  const second = await registerParticipant(original, { displayName: 'reviewer' });
  await selectParticipant(original, first.participantId);
  await relabelParticipant(original, first.participantId, 'api-agent');

  assert.notEqual(first.participantId, second.participantId);
  assert.equal((await resolveActiveParticipant(original)).participantId, first.participantId);
  assert.equal((await resolveActiveParticipant(original)).displayName, 'api-agent');

  await writeFile(join(clone, '.agentlink-placeholder'), 'clone target', 'utf8');
  await execFileAsync('cp', ['-R', join(original, '.agentlink'), join(clone, '.agentlink')]);
  await assert.rejects(readWorkspaceIdentity(clone), /workspace identity belongs to .*not/);
  const rotated = await rotateWorkspaceIdentity(clone);
  assert.notEqual(rotated.workspaceId, (await readWorkspaceIdentity(original)).workspaceId);
});

test('association serializes a concurrent target registration across the bus switch', async (t) => {
  const source = await temporaryWorkspace(t, 'agentlink-association-race-source-');
  const target = await temporaryWorkspace(t, 'agentlink-association-race-target-');
  const sourceContext = await initializeWorkspaceIdentity(source);
  await initializeWorkspaceIdentity(target);

  let association!: Promise<unknown>;
  let registration!: Promise<Awaited<ReturnType<typeof registerParticipant>>>;
  let registrationSettled = false;
  await withFileLock(join(sourceContext.association.busPath, 'locks'), 'participants', async () => {
    association = associateWorkspace(source, target);
    const associationLockOwner = join(target, '.agentlink', 'locks', 'workspace-association.lock');
    const deadline = Date.now() + 2_000;
    while (true) {
      try {
        await readFile(associationLockOwner, 'utf8');
        break;
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== 'ENOENT' || Date.now() >= deadline) throw error;
        await new Promise((resolve) => setTimeout(resolve, 10));
      }
    }
    registration = registerParticipant(target, { displayName: 'raced participant', select: false });
    void registration.then(
      () => { registrationSettled = true; },
      () => { registrationSettled = true; },
    );
    await new Promise((resolve) => setTimeout(resolve, 75));
    assert.equal(registrationSettled, false, 'registration must wait until the target association switch commits');
  }, { timeoutMs: 5_000 });

  await association;
  const registered = await registration;
  assert.equal(
    (await listParticipants(target)).some((participant) => participant.participantId === registered.participantId),
    true,
    'a successfully returned registration must remain visible on the associated bus',
  );
});

test('process-configured actors stay bound when the checkout default changes', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-process-actor-');
  await initializeWorkspaceIdentity(cwd);
  const owner = await resolveActiveParticipant(cwd);
  const conversation = await createConversation(cwd, { id: 'actor-process', topic: 'Actor process binding' });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  const reviewer = await registerParticipant(cwd, { displayName: 'reviewer' });
  await joinConversation(cwd, conversation.id);

  const appendScript = `import { appendMessage } from ${JSON.stringify(storeModulePath)}; await appendMessage(process.argv[1], 'actor-process', { role: 'assistant', body: 'owner process' });`;
  await execFileAsync(process.execPath, ['--input-type=module', '-e', appendScript, cwd], {
    env: { ...process.env, AGENTLINK_PARTICIPANT_ID: owner.participantId },
  });
  await appendMessage(cwd, conversation.id, { role: 'assistant', body: 'reviewer process' });

  const messages = (await readConversation(cwd, conversation.id)).messages;
  assert.deepEqual(messages.map((message) => message.participantId), [owner.participantId, reviewer.participantId]);
});

test('approvals bind to current revision and participant id while status-only transitions preserve sufficiency', async (t) => {
  const source = await temporaryWorkspace(t, 'agentlink-approval-source-');
  const peer = await temporaryWorkspace(t, 'agentlink-approval-peer-');
  await initializeWorkspaceIdentity(source);
  await initializeWorkspaceIdentity(peer);
  const sourceActor = await resolveActiveParticipant(source);
  const conversation = await createConversation(source, { id: 'approval', topic: 'Approval gate', requiredApprovals: 2 });
  await writeConversationContract(source, { conversationId: conversation.id, topic: conversation.topic });
  await associateWorkspace(source, peer, { conversationId: conversation.id });
  await joinConversation(peer, conversation.id);

  const initial = await readContractState(source, conversation.id);
  await approveConversation(source, conversation.id, {});
  await relabelParticipant(source, sourceActor.participantId, 'renamed-owner');
  await assert.rejects(approveConversation(source, conversation.id, {}), /already approved revision/);
  await approveConversation(peer, conversation.id, {});
  await updateConversationContract(source, conversation.id, { status: 'Accepted' });
  assert.equal((await readContractState(source, conversation.id)).revision, initial.revision);

  await updateConversationContract(source, conversation.id, {
    sections: [{ heading: 'Agreed Changes', content: 'A substantive new revision' }],
    status: 'Proposed',
  });
  const changed = await readContractState(source, conversation.id);
  assert.notEqual(changed.revision, initial.revision);
  await assert.rejects(
    updateConversationContract(source, conversation.id, { status: 'Accepted' }),
    /has 0\/2 approvals for revision/,
  );
});

test('owner revocation preserves audit records but removes participant eligibility and current quorum', async (t) => {
  const source = await temporaryWorkspace(t, 'agentlink-revoke-source-');
  const peer = await temporaryWorkspace(t, 'agentlink-revoke-peer-');
  await initializeWorkspaceIdentity(source);
  const conversation = await createConversation(source, { id: 'revoke', topic: 'Revocation', requiredApprovals: 2 });
  await writeConversationContract(source, { conversationId: conversation.id, topic: conversation.topic });
  await associateWorkspace(source, peer, { conversationId: conversation.id });
  const joined = await joinConversation(peer, conversation.id);
  const revision = (await readContractState(source, conversation.id)).revision!;
  await approveConversation(source, conversation.id, { revision });
  await approveConversation(peer, conversation.id, { revision });
  assert.equal(countRevisionApprovals(await readConversation(source, conversation.id), revision), 2);

  await revokeConversationParticipant(source, conversation.id, joined.participantId);
  const revoked = await readConversation(source, conversation.id);
  assert.equal(revoked.approvals.length, 2, 'historical approval audit remains append-only');
  assert.equal(revoked.participantIds.includes(joined.participantId), false);
  assert.equal(revoked.revokedParticipantIds.includes(joined.participantId), true);
  assert.equal(countRevisionApprovals(revoked, revision), 1);
  const summary = (await listConversations(source)).find((candidate) => candidate.id === conversation.id)!;
  assert.equal(summary.currentApprovalCount, 1);
  assert.equal(Object.hasOwn(summary, 'approvals'), false, 'listings expose current quorum, not raw historical approval arrays');
  await assert.rejects(joinConversation(peer, conversation.id), /revoked/i);
  await assert.rejects(approveConversation(peer, conversation.id, { revision }), /eligible|revoked/i);
  await assert.rejects(updateConversationContract(source, conversation.id, { status: 'Accepted' }), /1\/2 approvals/);
});

test('same-call content edit and Accepted gate is atomic and rejects stale revisions', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-atomic-gate-');
  await initializeWorkspaceIdentity(cwd);
  const conversation = await createConversation(cwd, { id: 'atomic', topic: 'Atomic gate', requiredApprovals: 1 });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  await approveConversation(cwd, conversation.id, {});
  const before = await readContractState(cwd, conversation.id);

  await assert.rejects(
    updateConversationContract(cwd, conversation.id, {
      expectedRevision: before.revision!,
      sections: [{ heading: 'Agreed Changes', content: 'Sneak in after approval' }],
      status: 'Accepted',
    }),
    /has 0\/1 approvals for revision/,
  );
  const unchanged = await readContractState(cwd, conversation.id);
  assert.equal(unchanged.revision, before.revision);
  assert.equal(unchanged.status, before.status);
  assert.doesNotMatch(await readFile(unchanged.path, 'utf8'), /Sneak in/);

  await updateConversationContract(cwd, conversation.id, {
    sections: [{ heading: 'Agreed Changes', content: 'Concurrent winner' }],
  });
  await assert.rejects(
    approveConversation(cwd, conversation.id, { revision: before.revision! }),
    /Cannot approve stale contract revision/,
  );
  await assert.rejects(
    updateConversationContract(cwd, conversation.id, {
      expectedRevision: before.revision!,
      sections: [{ heading: 'Agreed Changes', content: 'Stale loser' }],
    }),
    /stale contract revision/,
  );
});

test('approved lifecycle states cannot retain sufficiency after substantive edits', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-approved-edit-');
  const conversation = await createConversation(cwd, { id: 'approved-edit', topic: 'Approved edit', requiredApprovals: 1 });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  await approveConversation(cwd, conversation.id);
  await updateConversationContract(cwd, conversation.id, { status: 'Accepted' });

  await assert.rejects(
    updateConversationContract(cwd, conversation.id, {
      sections: [{ heading: 'Agreed Changes', content: 'Unapproved replacement' }],
    }),
    /has 0\/1 approvals for revision/,
  );
  assert.equal((await readContractState(cwd, conversation.id)).status, 'Accepted');
  assert.doesNotMatch(await readFile((await readContractState(cwd, conversation.id)).path, 'utf8'), /Unapproved replacement/);

  const proposed = await updateConversationContract(cwd, conversation.id, {
    sections: [{ heading: 'Agreed Changes', content: 'Replacement under review' }],
    status: 'Proposed',
  });
  assert.equal(proposed.status, 'Proposed');
});

test('editing the generated compatibility view is detected before authoritative mutation', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-compat-edit-');
  const conversation = await createConversation(cwd, { id: 'compat-edit', topic: 'Compatibility edit' });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  const before = await readContractState(cwd, conversation.id);
  await writeFile(join(cwd, '.agentlink', 'CONTRACT.md'), '# hand edited compatibility file\n', 'utf8');

  await assert.rejects(
    updateConversationContract(cwd, conversation.id, { status: 'Proposed' }),
    /generated compatibility view was modified.*--refresh/i,
  );
  assert.equal((await readContractState(cwd, conversation.id)).status, 'Draft');
  assert.equal((await readContractState(cwd, conversation.id)).revision, before.revision);
});

test('cross-process contract updates merge separate sections and reject one same-revision loser', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-process-contract-');
  const conversation = await createConversation(cwd, { id: 'contract-processes', topic: 'Contract process safety' });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  const updateScript = `import { updateConversationContract } from ${JSON.stringify(contractModulePath)}; await updateConversationContract(process.argv[1], 'contract-processes', { sections: [{ heading: process.argv[2], content: process.argv[3] }], ...(process.argv[4] ? { expectedRevision: process.argv[4] } : {}) });`;

  await Promise.all([
    execFileAsync(process.execPath, ['--input-type=module', '-e', updateScript, cwd, 'Repo A', 'A change', '']),
    execFileAsync(process.execPath, ['--input-type=module', '-e', updateScript, cwd, 'Repo B', 'B change', '']),
  ]);
  const merged = await readFile((await readContractState(cwd, conversation.id)).path, 'utf8');
  assert.match(merged, /## Repo A\s+A change/);
  assert.match(merged, /## Repo B\s+B change/);

  const revision = (await readContractState(cwd, conversation.id)).revision!;
  const contenders = await Promise.allSettled([
    execFileAsync(process.execPath, ['--input-type=module', '-e', updateScript, cwd, 'Repo A', 'winner one', revision]),
    execFileAsync(process.execPath, ['--input-type=module', '-e', updateScript, cwd, 'Repo A', 'winner two', revision]),
  ]);
  assert.equal(contenders.filter((result) => result.status === 'fulfilled').length, 1);
  assert.equal(contenders.filter((result) => result.status === 'rejected').length, 1);
});

test('interrupted contract, timeline, and compatibility writes roll forward exactly once on reopen', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-transaction-recovery-');
  const conversation = await createConversation(cwd, { id: 'recovery', topic: 'Transaction recovery', requiredApprovals: 1 });
  await writeConversationContract(cwd, { conversationId: conversation.id, topic: conversation.topic });
  await approveConversation(cwd, conversation.id);
  const childUpdate = `import { updateConversationContract } from ${JSON.stringify(contractModulePath)}; await updateConversationContract(process.argv[1], 'recovery', JSON.parse(process.argv[2]));`;
  const interrupt = (afterWrite: number, update: object) => execFileAsync(
    process.execPath,
    ['--input-type=module', '-e', childUpdate, cwd, JSON.stringify(update)],
    { env: {
      ...process.env,
      AGENTLINK_TEST_FAIL_TRANSACTION_KEY: 'conversation-recovery',
      AGENTLINK_TEST_CRASH_AFTER_TRANSACTION_WRITE: String(afterWrite),
    } },
  );

  await assert.rejects(interrupt(1, { sections: [{ heading: 'Agreed Changes', content: 'Recovered edit' }], status: 'Proposed' }));
  const recoveredEdit = await readContractState(cwd, conversation.id);
  assert.equal(recoveredEdit.status, 'Proposed');
  assert.match(await readFile(recoveredEdit.path, 'utf8'), /Recovered edit/);
  assert.equal(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), await readFile(recoveredEdit.path, 'utf8'));
  await approveConversation(cwd, conversation.id, { revision: recoveredEdit.revision });

  await assert.rejects(interrupt(2, { status: 'Accepted', expectedRevision: recoveredEdit.revision }));
  const accepted = await readContractState(cwd, conversation.id);
  const hydrated = await readConversation(cwd, conversation.id);
  assert.equal(accepted.status, 'Accepted');
  assert.equal(countRevisionApprovals(hydrated, accepted.revision!), 1, 'recovery must not manufacture or lose quorum');
  assert.equal(await readFile(join(cwd, '.agentlink', 'CONTRACT.md'), 'utf8'), await readFile(accepted.path, 'utf8'));

  const audits = (await readConversationRecords(cwd, conversation.id)).filter((record) => record.type === 'contract_mutation');
  assert.equal(audits.length, 3, 'initialization, edit, and acceptance each retain one audit record');
  assert.equal(new Set(audits.map((record) => record.transactionId)).size, 3);
  const context = await initializeWorkspaceIdentity(cwd);
  assert.deepEqual(await readdir(join(context.association.busPath, 'transactions')), []);
  assert.equal((await updateConversationContract(cwd, conversation.id, { status: 'Implemented' })).status, 'Implemented', 'recovery must not poison or steal the conversation lock');
});

test('bounded stale-lock recovery never steals a lock from a live process', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-live-lock-');
  const locks = join(cwd, 'locks');
  const ready = join(cwd, 'ready');
  const holderScript = `import { withFileLock } from ${JSON.stringify(atomicModulePath)}; import { writeFile } from 'node:fs/promises'; await withFileLock(process.argv[1], 'shared', async () => { await writeFile(process.argv[2], 'ready'); await new Promise((resolve) => setTimeout(resolve, 350)); });`;
  const holder = execFileAsync(process.execPath, ['--input-type=module', '-e', holderScript, locks, ready]);
  for (let attempt = 0; attempt < 100; attempt += 1) {
    try {
      await readFile(ready, 'utf8');
      break;
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 5));
    }
  }
  const contenderScript = `import { withFileLock } from ${JSON.stringify(atomicModulePath)}; await withFileLock(process.argv[1], 'shared', async () => {}, { timeoutMs: 100, staleMs: 20, retryMs: 5 });`;
  await assert.rejects(
    execFileAsync(process.execPath, ['--input-type=module', '-e', contenderScript, locks]),
    /Timed out acquiring lock shared/,
  );
  await holder;
  await execFileAsync(process.execPath, ['--input-type=module', '-e', contenderScript, locks]);
});

test('bounded lock recovery removes an aged lock owned by a dead process', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-dead-lock-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  await mkdir(lock, { recursive: true });
  await writeFile(join(lock, 'owner.json'), `${JSON.stringify({ pid: 2_147_483_647, acquiredAt: '2000-01-01T00:00:00.000Z' })}\n`, 'utf8');
  const old = new Date('2000-01-01T00:00:00.000Z');
  await utimes(lock, old, old);
  let acquired = false;
  await withFileLock(locks, 'shared', async () => {
    acquired = true;
  }, { timeoutMs: 200, staleMs: 10, retryMs: 5 });
  assert.equal(acquired, true);
});

test('bounded lock recovery removes an orphaned sibling reclaim claim', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-orphan-reclaim-claim-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  await mkdir(lock, { recursive: true });
  await writeFile(join(lock, 'owner.json'), `${JSON.stringify({
    pid: 2_147_483_647,
    token: 'dead-owner',
    acquiredAt: '2000-01-01T00:00:00.000Z',
  })}\n`, 'utf8');
  const old = new Date('2000-01-01T00:00:00.000Z');
  await utimes(lock, old, old);

  // A reclaimer can crash after exclusively creating this sibling and before
  // writing owner metadata or entering its cleanup path.
  await writeFile(`${lock}.reclaim`, '', 'utf8');
  const legacyClaim = `${lock}.reclaim`;
  const legacyDetails = await lstat(legacyClaim);
  const successorIdentity = createHash('sha256')
    .update(`legacy:${legacyDetails.dev}:${legacyDetails.ino}:${legacyDetails.birthtimeMs}`)
    .digest('hex')
    .slice(0, 32);
  const deadSuccessor = `${legacyClaim}.successor-${successorIdentity}`;
  await writeFile(deadSuccessor, `${JSON.stringify({
    pid: 2_147_483_647,
    token: 'dead-reclaim-successor',
  })}\n`, 'utf8');
  await utimes(legacyClaim, old, old);
  await utimes(deadSuccessor, old, old);

  let acquired = false;
  await withFileLock(locks, 'shared', async () => {
    acquired = true;
  }, { timeoutMs: 250, staleMs: 10, retryMs: 2 });
  assert.equal(acquired, true);
  assert.deepEqual(await readdir(locks), [], 'recovery must not leave a lock or reclaim claim behind');
});

test('a delayed reclaimer does not apply a dead-owner decision to a fresh lock incarnation', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-lock-incarnation-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  const barrier = join(cwd, 'barrier');
  await mkdir(lock, { recursive: true });
  await mkdir(barrier);
  await writeFile(join(lock, 'owner.json'), `${JSON.stringify({
    pid: 2_147_483_647,
    token: 'dead-owner',
    acquiredAt: '2000-01-01T00:00:00.000Z',
  })}\n`, 'utf8');
  const old = new Date('2000-01-01T00:00:00.000Z');
  await utimes(lock, old, old);

  const worker = `import { withFileLock } from ${JSON.stringify(atomicModulePath)}; await withFileLock(process.argv[1], 'shared', async () => {}, { timeoutMs: 100, staleMs: 10_000, retryMs: 2 });`;
  const contender = execFileAsync(process.execPath, ['--input-type=module', '-e', worker, locks], {
    env: { ...process.env, AGENTLINK_TEST_RECLAIM_BARRIER_DIRECTORY: barrier },
  });
  for (let attempt = 0; attempt < 200; attempt += 1) {
    if (await readFile(join(barrier, 'ready'), 'utf8').then(() => true, () => false)) break;
    await new Promise((resolve) => setTimeout(resolve, 2));
  }
  assert.equal(await readFile(join(barrier, 'ready'), 'utf8').then(() => true, () => false), true, 'reclaimer did not reach its bounded barrier');

  await rm(lock, { recursive: true });
  await mkdir(lock);
  await writeFile(join(barrier, 'continue'), 'continue\n', 'utf8');
  await assert.rejects(contender, /Timed out acquiring lock shared/);
  assert.equal((await readdir(lock)).length, 0, 'fresh ownerless incarnation must remain for its full stale window');
});

test('orphan reaping preserves a live fully published reclaim claim', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-live-reclaim-claim-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  const claim = `${lock}.reclaim`;
  await mkdir(lock, { recursive: true });
  await writeFile(join(lock, 'owner.json'), `${JSON.stringify({ pid: 2_147_483_647, token: 'dead-owner' })}\n`, 'utf8');
  await writeFile(claim, `${JSON.stringify({ pid: process.pid, token: 'live-claim' })}\n`, 'utf8');
  const old = new Date('2000-01-01T00:00:00.000Z');
  await utimes(lock, old, old);
  await utimes(claim, old, old);

  await assert.rejects(
    withFileLock(locks, 'shared', async () => {}, { timeoutMs: 40, staleMs: 1, retryMs: 2 }),
    /Timed out acquiring lock shared/,
  );
  assert.match(await readFile(claim, 'utf8'), /live-claim/, 'a live claim must not be reaped because of age');
});

test('orphan reaping cannot remove a replacement reclaim-claim incarnation', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-reclaim-claim-incarnation-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  const claim = `${lock}.reclaim`;
  const barrier = join(cwd, 'barrier');
  await mkdir(locks, { recursive: true });
  await mkdir(barrier);
  await writeFile(lock, `${JSON.stringify({ pid: 2_147_483_647, token: 'dead-lock' })}\n`, 'utf8');
  await writeFile(claim, `${JSON.stringify({ pid: 2_147_483_647, token: 'dead-claim' })}\n`, 'utf8');

  const worker = `import { withFileLock } from ${JSON.stringify(atomicModulePath)}; await withFileLock(process.argv[1], 'shared', async () => {}, { timeoutMs: 80, staleMs: 1, retryMs: 2 });`;
  const contender = execFileAsync(process.execPath, ['--input-type=module', '-e', worker, locks], {
    env: { ...process.env, AGENTLINK_TEST_RECLAIM_CLAIM_BARRIER_DIRECTORY: barrier },
  });
  for (let attempt = 0; attempt < 200; attempt += 1) {
    if (await readFile(join(barrier, 'ready'), 'utf8').then(() => true, () => false)) break;
    await new Promise((resolve) => setTimeout(resolve, 2));
  }
  assert.equal(await readFile(join(barrier, 'ready'), 'utf8').then(() => true, () => false), true, 'reaper did not reach its bounded barrier');

  await rm(claim);
  await writeFile(claim, `${JSON.stringify({ pid: process.pid, token: 'live-replacement' })}\n`, 'utf8');
  await writeFile(join(barrier, 'continue'), 'continue\n', 'utf8');

  await assert.rejects(contender, /Timed out acquiring lock shared/);
  assert.match(await readFile(claim, 'utf8'), /live-replacement/, 'replacement claim incarnation must survive');
});

test('fresh workspace initialization is consistent across competing processes', async (t) => {
  const root = await temporaryWorkspace(t, 'agentlink-concurrent-init-');
  const worker = `import { initializeWorkspaceIdentity } from ${JSON.stringify(workspaceModulePath)}; await initializeWorkspaceIdentity(process.argv[1]);`;
  for (let trial = 0; trial < 8; trial += 1) {
    const cwd = join(root, `workspace-${trial}`);
    await mkdir(cwd);
    await Promise.all(Array.from({ length: 4 }, () => execFileAsync(process.execPath, ['--input-type=module', '-e', worker, cwd])));
    const context = await initializeWorkspaceIdentity(cwd);
    assert.equal(context.association.busId, context.bus.busId);
  }
});

test('a stale-lock reclaimer never mutates or claims a live published owner record', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-live-lock-reclaim-barrier-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  let signalAcquired!: () => void;
  let releaseOwner!: () => void;
  const acquired = new Promise<void>((resolve) => { signalAcquired = resolve; });
  const release = new Promise<void>((resolve) => { releaseOwner = resolve; });
  const holder = withFileLock(locks, 'shared', async () => {
    signalAcquired();
    await release;
  });
  await acquired;

  assert.equal((await lstat(lock)).isFile(), true, 'owner metadata must be completely published as the lock record');
  let observedReclaimClaim = false;
  let contenderDone = false;
  try {
    const contender = assert.rejects(
      withFileLock(locks, 'shared', async () => {}, { timeoutMs: 50, staleMs: -1, retryMs: 1 }),
      /Timed out acquiring lock shared/,
    ).finally(() => { contenderDone = true; });
    while (!contenderDone) {
      if ((await readdir(locks)).includes('shared.lock.reclaim')) observedReclaimClaim = true;
      await new Promise<void>((resolve) => setImmediate(resolve));
    }
    await contender;
  } finally {
    releaseOwner();
    await holder;
  }

  assert.equal(
    observedReclaimClaim,
    false,
    'a contender must not create a reclaim claim for a live owner',
  );
  assert.deepEqual(await readdir(locks), [], 'owner release must clean both lock and reclaim claim paths');
});

test('competing stale-lock reclaimers serialize and do not remove a new live owner', async (t) => {
  const cwd = await temporaryWorkspace(t, 'agentlink-lock-reclaim-race-');
  const locks = join(cwd, 'locks');
  const lock = join(locks, 'shared.lock');
  const critical = join(cwd, 'critical');
  await mkdir(lock, { recursive: true });
  await writeFile(join(lock, 'owner.json'), `${JSON.stringify({ pid: 2_147_483_647, token: 'dead-owner', acquiredAt: '2000-01-01T00:00:00.000Z' })}\n`, 'utf8');
  const old = new Date('2000-01-01T00:00:00.000Z');
  await utimes(lock, old, old);
  const worker = `
import { withFileLock } from ${JSON.stringify(atomicModulePath)};
import { open, rm } from 'node:fs/promises';
await withFileLock(process.argv[1], 'shared', async () => {
  const handle = await open(process.argv[2], 'wx');
  await new Promise((resolve) => setTimeout(resolve, 75));
  await handle.close();
  await rm(process.argv[2]);
}, { timeoutMs: 2000, staleMs: 10, retryMs: 2 });`;
  await Promise.all([
    execFileAsync(process.execPath, ['--input-type=module', '-e', worker, locks, critical]),
    execFileAsync(process.execPath, ['--input-type=module', '-e', worker, locks, critical]),
  ]);
});

test('cross-process appends and approvals retain all distinct records', async (t) => {
  const source = await temporaryWorkspace(t, 'agentlink-process-source-');
  const peer = await temporaryWorkspace(t, 'agentlink-process-peer-');
  await initializeWorkspaceIdentity(source);
  await initializeWorkspaceIdentity(peer);
  const conversation = await createConversation(source, { id: 'processes', topic: 'Process safety', requiredApprovals: 2 });
  await writeConversationContract(source, { conversationId: conversation.id, topic: conversation.topic });
  await associateWorkspace(source, peer, { conversationId: conversation.id });
  await joinConversation(peer, conversation.id);

  const appendScript = `import { appendMessage } from ${JSON.stringify(storeModulePath)}; await appendMessage(process.argv[1], 'processes', { role: 'assistant', body: process.argv[2] });`;
  const approvalScript = `import { approveConversation } from ${JSON.stringify(storeModulePath)}; await approveConversation(process.argv[1], 'processes', {});`;
  const children = [
    execFileAsync(process.execPath, ['--input-type=module', '-e', appendScript, source, 'source message']),
    execFileAsync(process.execPath, ['--input-type=module', '-e', appendScript, peer, 'peer message']),
    execFileAsync(process.execPath, ['--input-type=module', '-e', approvalScript, source]),
    execFileAsync(process.execPath, ['--input-type=module', '-e', approvalScript, peer]),
  ];
  await Promise.all(children);

  const updated = await readConversation(source, conversation.id);
  assert.deepEqual(updated.messages.map((message) => message.body).sort(), ['peer message', 'source message']);
  assert.equal(new Set(updated.approvals.map((approval) => approval.participantId)).size, 2);
  await updateConversationContract(source, conversation.id, { status: 'Accepted' });
});
